# This workflow will do a clean install of Node dependencies, build the source code and run tests across different versions of Node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/predate/

    strategy:
      matrix:
        # (2023-05-06)
        # v16: Maintenance LTS (end-of-life: 2023-09-11)
        # v18: Actice LTS (end-of-life: 2025-04-30)
        # v20: Current (end-of-life: 2026-04-30)
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
